---
apiVersion: v2
description: Piped is an alternative privacy-friendly YouTube frontend which is efficient by design.
name: piped
home: https://github.com/TeamPiped/Piped-Kubernetes
icon: https://raw.githubusercontent.com/TeamPiped/Piped/master/public/img/icons/logo.svg
sources:
  - https://github.com/TeamPiped/Piped
  - https://github.com/TeamPiped/Piped-Backend
  - https://github.com/TeamPiped/piped-proxy
  - https://github.com/TeamPiped/Piped-Kubernetes
keywords:
  - streaming
version: 8.1.15
appVersion: latest
kubeVersion: ">=1.29.0"
maintainers:
  - name: samip5  # Skyler Mäntysaari
    email: samip5@users.noreply.github.com
    url: https://github.com/samip5
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated image for `frontend` from latest@sha256:4554578404448359d6c713ee29a86660212a8a7e0fe6b812a79963084d2a56ff to latest@sha256:290196532c67822ba8bcd05af5d71d5ab71acdcd68aaa7c861bd23f431972e66
