---
apiVersion: v2
description: Piped is an alternative privacy-friendly YouTube frontend which is efficient by design.
name: piped
home: https://github.com/TeamPiped/Piped-Kubernetes
icon: https://raw.githubusercontent.com/TeamPiped/Piped/master/public/img/icons/logo.svg
sources:
  - https://github.com/TeamPiped/Piped
  - https://github.com/TeamPiped/Piped-Backend
  - https://github.com/TeamPiped/piped-proxy
  - https://github.com/TeamPiped/Piped-Kubernetes
keywords:
  - streaming
version: 8.1.29
appVersion: latest
kubeVersion: ">=1.29.0"
maintainers:
  - name: samip5  # Skyler Mäntysaari
    email: samip5@users.noreply.github.com
    url: https://github.com/samip5
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated image for `frontend` from latest@sha256:cd099e0a7b47dd473631bc600ca8b8e9faf3c21c834decb85b94d286e55eae48 to latest@sha256:1ce67163448941627a2abc51a1d622120331d8e55ef78b85a83dc2de8811616e
    - kind: changed
      description: Updated image for `ytproxy` from latest@sha256:9830472b0ef5a5ea52d686b5669d35df8377cb586ee577e1c5bb01ef51196ef7 to latest@sha256:8aba8ba9d8bd3321ae9b15434b8d8bb9ffa03d699b2feb8f654f242a667e8cf2
